GET http://localhost:3000/devices

###
GET http://localhost:3000/devices/5e64f0a61549627a75fe26fc

###
POST http://localhost:3000/devices
Content-Type: application/json

{
    "name": "dummy device 1",
    "project": "dummy project 1"
}

###

DELETE http://localhost:3000/devices/5e64f0a61549627a75fe26fc

###

PATCH  http://localhost:3000/devices/5e64f0a61549627a75fe26fc
Content-Type: application/json

{
    "name": "New device name"
}