GET http://localhost:3000/devices

###
GET http://localhost:3000/devices/5e64f0a61549627a75fe26fc

###
POST http://localhost:3000/devices
Content-Type: application/json

{
    "name": "Raspberry Pi",
    "project": "Webcam"
}

###

POST  http://localhost:3000/devices/delete/5e65378d77a0950e89bbd0bd

###

POST  http://localhost:3000/devices/update/5e6537ad77a0950e89bbd0be
Content-Type: application/json

{
    "name": "New device name"
}